name: springboot-playground
services:
  postgresql:
    image: postgres:18.0
    hostname: postgresql
    volumes:
      - data-postgresql:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    restart: no
    ports:
      - "5432:5432"

  springboot-note:
    image: springboot-note:0.0.1
    build:
      context: ./springboot-note
      dockerfile: Dockerfile
      tags:
        - springboot-note:0.0.1
    hostname: springboot-note
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - APP_KAFKA_BOOTSTRAP_SERVERS=kafka1:29092
      - APP_KAFKA_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    ports:
      - "8080:8080"
    restart: no
    depends_on:
      - postgresql
      - kafka1
      - kafka2
      - kafka3

  springboot-note-categorizer:
    image: springboot-note-categorizer:0.0.1
    build:
      context: ./springboot-note-categorizer
      dockerfile: Dockerfile
      tags:
        - springboot-note-categorizer:0.0.1
    hostname: springboot-note-categorizer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:29092
      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
    restart: no
    depends_on:
      - kafka1
      - kafka2
      - kafka3


  kafka1:
    image: confluentinc/cp-kafka:8.1.1
    hostname: kafka1
    ports:
      - "29092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 9
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093,2@kafka2:29093,3@kafka3:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'Kz0xa9FTRqK2236JAR6Y1A'
    restart: no

  kafka2:
    image: confluentinc/cp-kafka:8.1.1
    hostname: kafka2
    ports:
      - "29192:9092"
      - "9102:9101"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 9
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093,2@kafka2:29093,3@kafka3:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:29192'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:29092,CONTROLLER://kafka2:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'Kz0xa9FTRqK2236JAR6Y1A'
    restart: no

  kafka3:
    image: confluentinc/cp-kafka:8.1.1
    hostname: kafka3
    ports:
      - "29392:9092"
      - "9103:9101"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 9
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093,2@kafka2:29093,3@kafka3:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:29092,PLAINTEXT_HOST://localhost:29392'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka3:29092,CONTROLLER://kafka3:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'Kz0xa9FTRqK2236JAR6Y1A'
    restart: no

  schema-registry:
    image: confluentinc/cp-schema-registry:8.1.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka1:29092, kafka2:29092, kafka3:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  rest-proxy:
    image: confluentinc/cp-kafka-rest:8.1.1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    ports:
      - "8082:8082"
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka1:29092, kafka2:29092, kafka3:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'


  kafka-connect1:
    image: cp-kafka-connect-my:8.1.1
    build:
        context: ./docker/cp-kafka-connect-my
        dockerfile: Dockerfile
        tags:
          - cp-kafka-connect-my:8.1.1
    hostname: kafka-connect1
    restart: no
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka1:29092,kafka2:29092,kafka3:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'kafka-connect1'
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/kafka-connect-plugins"

  mongo:
    image: mongo:8.0.15
    hostname: mongo
    volumes:
      - data-mongo:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=playground
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    restart: no

  opensearch1:
    image: opensearchproject/opensearch:3.5.0
    hostname: opensearch1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch1
      - discovery.seed_hosts=opensearch1,opensearch2
      - cluster.initial_cluster_manager_nodes=opensearch1,opensearch2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=osPass@28g
    volumes:
      - data-opensearch1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: no

  opensearch2:
    image: opensearchproject/opensearch:3.5.0
    hostname: opensearch2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch2
      - discovery.seed_hosts=opensearch1,opensearch2
      - cluster.initial_cluster_manager_nodes=opensearch1,opensearch2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=osPass@28g
    volumes:
      - data-opensearch2:/usr/share/opensearch/data
    restart: no

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.5.0
    hostname: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch1:9200","https://opensearch2:9200"]'
    restart: no
    depends_on:
      - opensearch1
      - opensearch2

volumes:
  data-postgresql:
  data-mongo:
  data-opensearch1:
  data-opensearch2:
